### ISSUE TITLE
B2 refuses to login

### ISSUE THREAD

**Issue by DarthGandalf** [gaul/s3proxy#249]
```
$ cat s3proxy.conf
s3proxy.endpoint=http://127.0.0.1:8081
s3proxy.authorization=none
jclouds.provider=b2
jclouds.identity=xxxxxxxx
jclouds.credential=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
```
$ curl --request PUT http://localhost:8081/roatnaountor
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 </title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /roatnaountor. Reason:
<pre>    java.lang.IllegalStateException</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
</body>
</html>
```
```
$ java -DLOG_LEVEL=trace -jar s3proxy --properties s3proxy.conf
[s3proxy] I 12-19 16:08:50.905 main org.eclipse.jetty.util.log:186 |::] Logging initialized @8655ms
[s3proxy] I 12-19 16:08:51.196 main o.eclipse.jetty.server.Server:327 |::] jetty-9.2.z-SNAPSHOT
[s3proxy] I 12-19 16:08:51.445 main o.e.j.server.ServerConnector:266 |::] Started ServerConnector@3cd68{HTTP/1.1}{127.0.0.1:8081}
[s3proxy] I 12-19 16:08:51.449 main o.eclipse.jetty.server.Server:379 |::] Started @9212ms
[s3proxy] D 12-19 16:09:01.858 S3Proxy-13 o.gaul.s3proxy.S3ProxyHandler:270 |::] request: Request(PUT /roatnaountor)@394586
[s3proxy] T 12-19 16:09:01.864 S3Proxy-13 o.gaul.s3proxy.S3ProxyHandler:292 |::] header: User-Agent: curl/7.57.0
[s3proxy] T 12-19 16:09:01.866 S3Proxy-13 o.gaul.s3proxy.S3ProxyHandler:292 |::] header: Accept: */*
[s3proxy] T 12-19 16:09:01.868 S3Proxy-13 o.gaul.s3proxy.S3ProxyHandler:292 |::] header: Host: localhost:8081
[s3proxy] D 12-19 16:09:01.879 S3Proxy-13 o.gaul.s3proxy.S3ProxyHandler:1133 |::] Creating bucket with location: null
[s3proxy] T 12-19 16:09:01.978 S3Proxy-13 o.j.r.i.InvokeHttpMethod:47 |::] >> converting b2_create_bucket
[s3proxy] T 12-19 16:09:02.069 S3Proxy-13 o.j.r.i.RestAnnotationProcessor:47 |::] no annotations on class or invocation.getInvoked(): org.jclouds.b2.features.BucketApi.public abstract org.jclouds.b2.domain.Bucket org.jclouds.b2.features.BucketApi.createBucket(java.lang.String,org.jclouds.b2.domain.BucketType)
[s3proxy] T 12-19 16:09:02.072 S3Proxy-13 o.j.r.i.RestAnnotationProcessor:47 |::] no annotations on class or invocation.getInvoked(): org.jclouds.b2.B2Api.public abstract org.jclouds.b2.features.BucketApi org.jclouds.b2.B2Api.getBucketApi()
[s3proxy] T 12-19 16:09:02.075 S3Proxy-13 o.j.r.i.RestAnnotationProcessor:47 |::] no annotations on class or invocation.getInvoked(): org.jclouds.b2.features.BucketApi.public abstract org.jclouds.b2.domain.Bucket org.jclouds.b2.features.BucketApi.createBucket(java.lang.String,org.jclouds.b2.domain.BucketType)
[s3proxy] T 12-19 16:09:02.078 S3Proxy-13 o.j.r.i.RestAnnotationProcessor:47 |::] looking up default endpoint for org.jclouds.b2.features.BucketApi.public abstract org.jclouds.b2.domain.Bucket org.jclouds.b2.features.BucketApi.createBucket(java.lang.String,org.jclouds.b2.domain.BucketType)[roatnaountor, allPrivate]
[s3proxy] T 12-19 16:09:02.085 S3Proxy-13 o.j.r.i.RestAnnotationProcessor:47 |::] using default endpoint Optional.of(https://api.backblazeb2.com/) for org.jclouds.b2.features.BucketApi.public abstract org.jclouds.b2.domain.Bucket org.jclouds.b2.features.BucketApi.createBucket(java.lang.String,org.jclouds.b2.domain.BucketType)[roatnaountor, allPrivate]
[s3proxy] T 12-19 16:09:02.128 S3Proxy-13 o.j.r.i.RestAnnotationProcessor:47 |::] adding filter org.jclouds.b2.filters.RequestAuthorization@1391a72 from annotation on org.jclouds.b2.features.BucketApi
[s3proxy] T 12-19 16:09:02.329 S3Proxy-13 o.j.r.i.InvokeHttpMethod:47 |::] << converted b2_create_bucket to POST https://api.backblazeb2.com/b2api/v1/b2_create_bucket HTTP/1.1
[s3proxy] T 12-19 16:09:02.356 S3Proxy-13 o.j.r.i.InvokeHttpMethod:47 |::] << response from b2_create_bucket is parsed by ParseJson
[s3proxy] T 12-19 16:09:02.360 S3Proxy-13 o.j.r.i.InvokeHttpMethod:47 |::] << exceptions from b2_create_bucket are parsed by MapHttp4xxCodesToExceptions
[s3proxy] D 12-19 16:09:02.363 S3Proxy-13 o.j.r.i.InvokeHttpMethod:56 |::] >> invoking b2_create_bucket
[s3proxy] T 12-19 16:09:02.386 S3Proxy-13 o.j.r.i.InvokeHttpMethod:47 |::] >> converting b2_authorize_account
[s3proxy] T 12-19 16:09:02.389 S3Proxy-13 o.j.r.i.RestAnnotationProcessor:47 |::] no annotations on class or invocation.getInvoked(): org.jclouds.b2.features.AuthorizationApi.public abstract org.jclouds.b2.domain.Authorization org.jclouds.b2.features.AuthorizationApi.authorizeAccount()
[s3proxy] T 12-19 16:09:02.393 S3Proxy-13 o.j.r.i.RestAnnotationProcessor:47 |::] no annotations on class or invocation.getInvoked(): org.jclouds.b2.B2Api.public abstract org.jclouds.b2.features.AuthorizationApi org.jclouds.b2.B2Api.getAuthorizationApi()
[s3proxy] T 12-19 16:09:02.396 S3Proxy-13 o.j.r.i.RestAnnotationProcessor:47 |::] no annotations on class or invocation.getInvoked(): org.jclouds.b2.features.AuthorizationApi.public abstract org.jclouds.b2.domain.Authorization org.jclouds.b2.features.AuthorizationApi.authorizeAccount()
[s3proxy] T 12-19 16:09:02.398 S3Proxy-13 o.j.r.i.RestAnnotationProcessor:47 |::] looking up default endpoint for org.jclouds.b2.features.AuthorizationApi.public abstract org.jclouds.b2.domain.Authorization org.jclouds.b2.features.AuthorizationApi.authorizeAccount()[]
[s3proxy] T 12-19 16:09:02.402 S3Proxy-13 o.j.r.i.RestAnnotationProcessor:47 |::] using default endpoint Optional.of(https://api.backblazeb2.com/) for org.jclouds.b2.features.AuthorizationApi.public abstract org.jclouds.b2.domain.Authorization org.jclouds.b2.features.AuthorizationApi.authorizeAccount()[]
[s3proxy] T 12-19 16:09:02.425 S3Proxy-13 o.j.r.i.RestAnnotationProcessor:47 |::] adding filter org.jclouds.http.filters.BasicAuthentication@1e4576e from annotation on authorizeAccount
[s3proxy] T 12-19 16:09:02.443 S3Proxy-13 o.j.r.i.InvokeHttpMethod:47 |::] << converted b2_authorize_account to GET https://api.backblazeb2.com/b2api/v1/b2_authorize_account HTTP/1.1
[s3proxy] T 12-19 16:09:02.449 S3Proxy-13 o.j.r.i.InvokeHttpMethod:47 |::] << response from b2_authorize_account is parsed by ParseJson
[s3proxy] T 12-19 16:09:02.452 S3Proxy-13 o.j.r.i.InvokeHttpMethod:47 |::] << exceptions from b2_authorize_account are parsed by MapHttp4xxCodesToExceptions
[s3proxy] D 12-19 16:09:02.454 S3Proxy-13 o.j.r.i.InvokeHttpMethod:56 |::] >> invoking b2_authorize_account
[s3proxy] D 12-19 16:09:02.513 S3Proxy-13 o.j.h.i.JavaUrlHttpCommandExecutorService:56 |::] Sending request -487576823: GET https://api.backblazeb2.com/b2api/v1/b2_authorize_account HTTP/1.1
[s3proxy] D 12-19 16:09:02.516 S3Proxy-13 jclouds.headers:56 |::] >> GET https://api.backblazeb2.com/b2api/v1/b2_authorize_account HTTP/1.1
[s3proxy] D 12-19 16:09:02.519 S3Proxy-13 jclouds.headers:56 |::] >> Accept: application/json
[s3proxy] D 12-19 16:09:02.521 S3Proxy-13 jclouds.headers:56 |::] >> Authorization: Basic XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX==
[s3proxy] D 12-19 16:09:04.693 S3Proxy-13 o.j.h.h.BackoffLimitedRetryHandler:56 |::] Retry 1/5: delaying for 1029 ms: server error: [method=org.jclouds.b2.features.AuthorizationApi.public abstract org.jclouds.b2.domain.Authorization org.jclouds.b2.features.AuthorizationApi.authorizeAccount()[], request=GET https://api.backblazeb2.com/b2api/v1/b2_authorize_account HTTP/1.1]
[s3proxy] D 12-19 16:09:05.729 S3Proxy-13 o.j.h.i.JavaUrlHttpCommandExecutorService:56 |::] Sending request -487576823: GET https://api.backblazeb2.com/b2api/v1/b2_authorize_account HTTP/1.1
[s3proxy] D 12-19 16:09:05.732 S3Proxy-13 jclouds.headers:56 |::] >> GET https://api.backblazeb2.com/b2api/v1/b2_authorize_account HTTP/1.1
[s3proxy] D 12-19 16:09:05.735 S3Proxy-13 jclouds.headers:56 |::] >> Accept: application/json
[s3proxy] D 12-19 16:09:05.737 S3Proxy-13 jclouds.headers:56 |::] >> Authorization: Basic XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX==
[s3proxy] D 12-19 16:09:06.127 S3Proxy-13 o.j.h.h.BackoffLimitedRetryHandler:56 |::] Retry 2/5: delaying for 4342 ms: server error: [method=org.jclouds.b2.features.AuthorizationApi.public abstract org.jclouds.b2.domain.Authorization org.jclouds.b2.features.AuthorizationApi.authorizeAccount()[], request=GET https://api.backblazeb2.com/b2api/v1/b2_authorize_account HTTP/1.1]
[s3proxy] D 12-19 16:09:10.475 S3Proxy-13 o.j.h.i.JavaUrlHttpCommandExecutorService:56 |::] Sending request -487576823: GET https://api.backblazeb2.com/b2api/v1/b2_authorize_account HTTP/1.1
[s3proxy] D 12-19 16:09:10.477 S3Proxy-13 jclouds.headers:56 |::] >> GET https://api.backblazeb2.com/b2api/v1/b2_authorize_account HTTP/1.1
[s3proxy] D 12-19 16:09:10.480 S3Proxy-13 jclouds.headers:56 |::] >> Accept: application/json
[s3proxy] D 12-19 16:09:10.482 S3Proxy-13 jclouds.headers:56 |::] >> Authorization: Basic XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX==
[s3proxy] D 12-19 16:09:10.868 S3Proxy-13 o.j.h.h.BackoffLimitedRetryHandler:56 |::] Retry 3/5: delaying for 9390 ms: server error: [method=org.jclouds.b2.features.AuthorizationApi.public abstract org.jclouds.b2.domain.Authorization org.jclouds.b2.features.AuthorizationApi.authorizeAccount()[], request=GET https://api.backblazeb2.com/b2api/v1/b2_authorize_account HTTP/1.1]
[s3proxy] D 12-19 16:09:20.264 S3Proxy-13 o.j.h.i.JavaUrlHttpCommandExecutorService:56 |::] Sending request -487576823: GET https://api.backblazeb2.com/b2api/v1/b2_authorize_account HTTP/1.1
[s3proxy] D 12-19 16:09:20.266 S3Proxy-13 jclouds.headers:56 |::] >> GET https://api.backblazeb2.com/b2api/v1/b2_authorize_account HTTP/1.1
[s3proxy] D 12-19 16:09:20.269 S3Proxy-13 jclouds.headers:56 |::] >> Accept: application/json
[s3proxy] D 12-19 16:09:20.272 S3Proxy-13 jclouds.headers:56 |::] >> Authorization: Basic XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX==
[s3proxy] D 12-19 16:09:20.658 S3Proxy-13 o.j.h.h.BackoffLimitedRetryHandler:56 |::] Retry 4/5: delaying for 10000 ms: server error: [method=org.jclouds.b2.features.AuthorizationApi.public abstract org.jclouds.b2.domain.Authorization org.jclouds.b2.features.AuthorizationApi.authorizeAccount()[], request=GET https://api.backblazeb2.com/b2api/v1/b2_authorize_account HTTP/1.1]
[s3proxy] D 12-19 16:09:30.664 S3Proxy-13 o.j.h.i.JavaUrlHttpCommandExecutorService:56 |::] Sending request -487576823: GET https://api.backblazeb2.com/b2api/v1/b2_authorize_account HTTP/1.1
[s3proxy] D 12-19 16:09:30.667 S3Proxy-13 jclouds.headers:56 |::] >> GET https://api.backblazeb2.com/b2api/v1/b2_authorize_account HTTP/1.1
[s3proxy] D 12-19 16:09:30.669 S3Proxy-13 jclouds.headers:56 |::] >> Accept: application/json
[s3proxy] D 12-19 16:09:30.672 S3Proxy-13 jclouds.headers:56 |::] >> Authorization: Basic XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX==
[s3proxy] D 12-19 16:09:31.072 S3Proxy-13 o.j.h.h.BackoffLimitedRetryHandler:56 |::] Retry 5/5: delaying for 10000 ms: server error: [method=org.jclouds.b2.features.AuthorizationApi.public abstract org.jclouds.b2.domain.Authorization org.jclouds.b2.features.AuthorizationApi.authorizeAccount()[], request=GET https://api.backblazeb2.com/b2api/v1/b2_authorize_account HTTP/1.1]
[s3proxy] D 12-19 16:09:41.078 S3Proxy-13 o.j.h.i.JavaUrlHttpCommandExecutorService:56 |::] Sending request -487576823: GET https://api.backblazeb2.com/b2api/v1/b2_authorize_account HTTP/1.1
[s3proxy] D 12-19 16:09:41.081 S3Proxy-13 jclouds.headers:56 |::] >> GET https://api.backblazeb2.com/b2api/v1/b2_authorize_account HTTP/1.1
[s3proxy] D 12-19 16:09:41.083 S3Proxy-13 jclouds.headers:56 |::] >> Accept: application/json
[s3proxy] D 12-19 16:09:41.086 S3Proxy-13 jclouds.headers:56 |::] >> Authorization: Basic MjNkYzMzZGU1YTdmOjAwMTYxZjliMmQ4NjQ2MWE1OTQzNGNmNDU1Y2Q4MjJiZTNhYzY5YWExMQ==
[s3proxy] E 12-19 16:09:41.469 S3Proxy-13 o.j.h.h.BackoffLimitedRetryHandler:88 |::] Cannot retry after server error, command has exceeded retry limit 5: [method=org.jclouds.b2.features.AuthorizationApi.public abstract org.jclouds.b2.domain.Authorization org.jclouds.b2.features.AuthorizationApi.authorizeAccount()[], request=GET https://api.backblazeb2.com/b2api/v1/b2_authorize_account HTTP/1.1]
[s3proxy] W 12-19 16:09:41.487 S3Proxy-13 o.e.jetty.server.HttpChannel:396 |::] /roatnaountor
java.lang.IllegalStateException: null
	at sun.security.ec.ECDHKeyAgreement.deriveKey(Native Method)
	at sun.security.ec.ECDHKeyAgreement.engineGenerateSecret(ECDHKeyAgreement.java:130)
	at sun.security.ec.ECDHKeyAgreement.engineGenerateSecret(ECDHKeyAgreement.java:163)
	at javax.crypto.KeyAgreement.generateSecret(KeyAgreement.java:648)
	at sun.security.ssl.ECDHCrypt.getAgreedSecret(ECDHCrypt.java:102)
	at sun.security.ssl.ClientHandshaker.serverHelloDone(ClientHandshaker.java:1061)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:348)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:961)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at org.jclouds.http.internal.JavaUrlHttpCommandExecutorService.invoke(JavaUrlHttpCommandExecutorService.java:96)
	at org.jclouds.http.internal.JavaUrlHttpCommandExecutorService.invoke(JavaUrlHttpCommandExecutorService.java:65)
	at org.jclouds.http.internal.BaseHttpCommandExecutorService.invoke(BaseHttpCommandExecutorService.java:100)
	at org.jclouds.rest.internal.InvokeHttpMethod.invoke(InvokeHttpMethod.java:90)
	at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:73)
	at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:44)
	at org.jclouds.reflect.FunctionalReflection$FunctionalInvocationHandler.handleInvocation(FunctionalReflection.java:117)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
	at com.sun.proxy.$Proxy56.authorizeAccount(Unknown Source)
	at org.jclouds.b2.config.B2HttpApiModule$1.get(B2HttpApiModule.java:73)
	at org.jclouds.b2.config.B2HttpApiModule$1.get(B2HttpApiModule.java:70)
	at org.jclouds.rest.suppliers.MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier$SetAndThrowAuthorizationExceptionSupplierBackedLoader.load(MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.java:75)
	at org.jclouds.rest.suppliers.MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier$SetAndThrowAuthorizationExceptionSupplierBackedLoader.load(MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.java:57)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
	at org.jclouds.rest.suppliers.MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.get(MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.java:150)
	at org.jclouds.b2.filters.RequestAuthorization.filter(RequestAuthorization.java:44)
	at org.jclouds.http.internal.BaseHttpCommandExecutorService.invoke(BaseHttpCommandExecutorService.java:92)
	at org.jclouds.rest.internal.InvokeHttpMethod.invoke(InvokeHttpMethod.java:90)
	at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:73)
	at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:44)
	at org.jclouds.reflect.FunctionalReflection$FunctionalInvocationHandler.handleInvocation(FunctionalReflection.java:117)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
	at com.sun.proxy.$Proxy44.createBucket(Unknown Source)
	at org.jclouds.b2.blobstore.B2BlobStore.createContainerInLocation(B2BlobStore.java:150)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:37)
	at com.sun.proxy.$Proxy42.createContainerInLocation(Unknown Source)
	at org.gaul.s3proxy.S3ProxyHandler.handleContainerCreate(S3ProxyHandler.java:1143)
	at org.gaul.s3proxy.S3ProxyHandler.doHandle(S3ProxyHandler.java:620)
	at org.gaul.s3proxy.S3ProxyHandlerJetty.handle(S3ProxyHandlerJetty.java:70)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)

```
Version 1.5.3
I verified that `Authorization: Basic` value is correct base64 of `accid:appkey`, and `b2` command line tool works with the same credentials.
Also I verified that s3proxy works as expected with filesystem provider.

How to check full body and headers of HTTP requests and responses?

**Comment by gaul** [comment]
You can get the full body responses via:

```
java -DLOG_LEVEL=trace -Djclouds.wire=debug -jar target/s3proxy --properties configs/b2.conf
```

I am not sure why you have issues; I can successfully complete the same operation against B2.

**Comment by DarthGandalf** [comment]
That doesn't show any more details. But upon further investigation of stack trace, this looks like SSL handshake doesn't work, so this is OpenJDK issue, and server can't send anything at all, so there's nothing to show.
I followed https://stackoverflow.com/questions/37167189/illegalstateexception-thrown-by-maven-ssl-related-when-downloading-project-de to fix it.
Sorry for noise.
