### ISSUE TITLE
listObjects() failed by "Unable to get list of extended attributes: Operation not supported"

### ISSUE THREAD

**Issue by JasperHot** [gaul/s3proxy#279]
Hi,
I run s3proxy in a Linux server.
The basedir is "/home/awss3/s3test", then I create sub-folder "folder".
But I can't list the object "/home/awss3/s3test/folder" by AWS S3 API. 
I'm not sure if it is caused by a FS without the extended attributes (i.e. user_xattr). Or some other reasons ?

Java code:
```java
ListObjectsRequest listObjectsRequest = new ListObjectsRequest().withBucketName("s3test").withPrefix("folder");
ObjectListing results=s3.listObjects(listObjectsRequest);
```

Error log:
```
2018-07-19 12:44:18.815 ERROR 26154 --- [nio-8080-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception 
[Request processing failed; nested exception is com.amazonaws.services.s3.model.AmazonS3Exception: java.nio.file.FileSystemException: /home/awss3/s3test/folder: Unable to get list of extended attributes: Operation not supported (Service: Amazon S3; Status Code: 500; Error Code: 500 java.nio.file.FileSystemException: /home/awss3/s3test/folder: Unable to get list of extended attributes: Operation not supported; Request ID: null), S3 Extended Request ID: null] with root cause

com.amazonaws.services.s3.model.AmazonS3Exception: java.nio.file.FileSystemException: /home/awss3/s3test/folder: Unable to get list of extended attributes: Operation not supported (Service: Amazon S3; Status Code: 500; Error Code: 500 java.nio.file.FileSystemException: /home/awss3/s3test/folder: Unable to get list of extended attributes: Operation not supported; Request ID: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1588) ~[aws-java-sdk-core-1.11.125.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1258) ~[aws-java-sdk-core-1.11.125.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1030) ~[aws-java-sdk-core-1.11.125.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:742) ~[aws-java-sdk-core-1.11.125.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:716) ~[aws-java-sdk-core-1.11.125.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699) ~[aws-java-sdk-core-1.11.125.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667) ~[aws-java-sdk-core-1.11.125.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649) ~[aws-java-sdk-core-1.11.125.jar:na]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513) ~[aws-java-sdk-core-1.11.125.jar:na]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4169) ~[aws-java-sdk-s3-1.11.125.jar:na]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4116) ~[aws-java-sdk-s3-1.11.125.jar:na]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4110) ~[aws-java-sdk-s3-1.11.125.jar:na]
	at com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:819) ~[aws-java-sdk-s3-1.11.125.jar:na]
...


[s3proxy] E 07-19 12:44:18.772 S3Proxy-17 o.j.f.s.i.FilesystemStorageStrategyImpl:93 |::] An error occurred while checking key s3test in container folder/
java.nio.file.FileSystemException: /home/awss3/s3test/folder: Unable to get list of extended attributes: Operation not supported
        at sun.nio.fs.LinuxUserDefinedFileAttributeView.list(LinuxUserDefinedFileAttributeView.java:121)
        at org.jclouds.filesystem.strategy.internal.FilesystemStorageStrategyImpl.buildPathAndChecksIfBlobExists(FilesystemStorageStrategyImpl.java:693)
        at org.jclouds.filesystem.strategy.internal.FilesystemStorageStrategyImpl.blobExists(FilesystemStorageStrategyImpl.java:288)
        at org.jclouds.blobstore.config.LocalBlobStore$1.apply(LocalBlobStore.java:246)
        at org.jclouds.blobstore.config.LocalBlobStore$1.apply(LocalBlobStore.java:242)
        at com.google.common.collect.Iterators$7.computeNext(Iterators.java:647)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
        at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
        at com.google.common.collect.Iterators$7.computeNext(Iterators.java:645)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
        at com.google.common.collect.Iterators.addAll(Iterators.java:356)
        at com.google.common.collect.Iterables.addAll(Iterables.java:350)
        at com.google.common.collect.Sets.newTreeSet(Sets.java:365)
        at org.jclouds.blobstore.config.LocalBlobStore.list(LocalBlobStore.java:249)
        at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:37)
        at com.sun.proxy.$Proxy40.list(Unknown Source)
        at org.gaul.s3proxy.S3ProxyHandler.handleBlobList(S3ProxyHandler.java:1239)
        at org.gaul.s3proxy.S3ProxyHandler.doHandle(S3ProxyHandler.java:584)
        at org.gaul.s3proxy.S3ProxyHandlerJetty.handle(S3ProxyHandlerJetty.java:70)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)
[s3proxy] W 07-19 12:44:18.772 S3Proxy-17 o.e.jetty.server.HttpChannel:396 |::] /s3test/?prefix=folder&delimiter=%2F&encoding-type=url
java.lang.RuntimeException: java.nio.file.FileSystemException: /home/awss3/s3test/folder: Unable to get list of extended attributes: Operation not supported
        at com.google.common.base.Throwables.propagate(Throwables.java:160)
        at org.jclouds.filesystem.strategy.internal.FilesystemStorageStrategyImpl.blobExists(FilesystemStorageStrategyImpl.java:292)
        at org.jclouds.blobstore.config.LocalBlobStore$1.apply(LocalBlobStore.java:246)
        at org.jclouds.blobstore.config.LocalBlobStore$1.apply(LocalBlobStore.java:242)
        at com.google.common.collect.Iterators$7.computeNext(Iterators.java:647)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
        at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
        at com.google.common.collect.Iterators$7.computeNext(Iterators.java:645)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
        at com.google.common.collect.Iterators.addAll(Iterators.java:356)
        at com.google.common.collect.Iterables.addAll(Iterables.java:350)
        at com.google.common.collect.Sets.newTreeSet(Sets.java:365)
        at org.jclouds.blobstore.config.LocalBlobStore.list(LocalBlobStore.java:249)
        at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:37)
        at com.sun.proxy.$Proxy40.list(Unknown Source)
        at org.gaul.s3proxy.S3ProxyHandler.handleBlobList(S3ProxyHandler.java:1239)
        at org.gaul.s3proxy.S3ProxyHandler.doHandle(S3ProxyHandler.java:584)
        at org.gaul.s3proxy.S3ProxyHandlerJetty.handle(S3ProxyHandlerJetty.java:70)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.file.FileSystemException: /home/awss3/s3test/folder: Unable to get list of extended attributes: Operation not supported
        at sun.nio.fs.LinuxUserDefinedFileAttributeView.list(LinuxUserDefinedFileAttributeView.java:121)
        at org.jclouds.filesystem.strategy.internal.FilesystemStorageStrategyImpl.buildPathAndChecksIfBlobExists(FilesystemStorageStrategyImpl.java:693)
        at org.jclouds.filesystem.strategy.internal.FilesystemStorageStrategyImpl.blobExists(FilesystemStorageStrategyImpl.java:288)
        ... 29 common frames omitted
```

BR/Jasper

**Comment by gaul** [comment]
Which file system does your basedir point at?  S3Proxy uses xattr but I believe should work without it, albeit without user metadata.

**Comment by JasperHot** [comment]
Folder "/home/awss3" is NFS mount. What should I do?

**Comment by martin-tarjanyi** [comment]
Hi,

I use S3 proxy with Docker for Windows.
I get the same exception when try to list objects in a bucket:

```
java.lang.RuntimeException: java.nio.file.FileSystemException: /data/xxx: Unable to get list of extended attributes: Not supported
at com.google.common.base.Throwables.propagate(Throwables.java:160)
at org.jclouds.filesystem.strategy.internal.FilesystemStorageStrategyImpl.blobExists(FilesystemStorageStrategyImpl.java:297)
at org.jclouds.blobstore.config.LocalBlobStore$1.apply(LocalBlobStore.java:248)
at org.jclouds.blobstore.config.LocalBlobStore$1.apply(LocalBlobStore.java:244)
```

Maybe it is also related to https://github.com/gaul/s3proxy/issues/155

**Comment by gaul** [comment]
Sorry for the delayed response; I had no way to test this until I wrote [libnoxattr](https://github.com/gaul/libnoxattr).

**Comment by gaul** [comment]
JDK 17 will add xattr support for macOS which should improve compatibility: https://bugs.openjdk.java.net/browse/JDK-8030048
