### ISSUE TITLE
Can we use S3ProxyRule in cucumber test 

### ISSUE THREAD

**Issue by MkJha** [gaul/s3proxy#281]
I have used S3ProxyRule  in junit testing. But while using it (similar way as used in junit) cucumber code , the s3 proxy jetty server doesn't get started hence the endpoint is null.

**Comment by gaul** [comment]
Does Cucumber support `org.junit.Rule`?  Sorry I don't know much about this; could you provide an example?  @ddcprg may know more.

**Comment by MkJha** [comment]
Anyway, i used java way as explained:
Instantiate S3Proxy by creating a backend BlobStore object and a frontend S3Proxy object. An example configuring the filesystem backend and listening on port 8080 and it worked.

I want to start the proxy on https (not http), but i am facing issue:

com.amazonaws.SdkClientException: Unable to execute HTTP request: Unrecognized SSL message, plaintext connection?
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1116)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1066)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4365)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4312)
	at com.amazonaws.services.s3.AmazonS3Client.headBucket(AmazonS3Client.java:1343)
	at com.amazonaws.services.s3.AmazonS3Client.doesBucketExist(AmazonS3Client.java:1283)

It would be great if you help me like how to configure and use that from amzons3 client.

**Comment by MkJha** [comment]
I assume code should look like this:

proxy code: 
Properties properties = new Properties();
    	properties.setProperty("jclouds.filesystem.basedir", "src/test/resources/");

    	BlobStoreContext context = ContextBuilder
    	        .newBuilder("filesystem")
    	        .overrides(properties)
    	        .build(BlobStoreContext.class);
    	s3Proxy = S3Proxy.builder()
    	        .blobStore(context.getBlobStore())
    	       // .endpoint(URI.create(S3_PROXY_ENDPOINT)).awsAuthentication(AuthenticationType.AWS_V2_OR_V4, AWS_ACCESS_KEY, AWS_SECRET_KEY)
    	        .secureEndpoint(URI.create(S3_PROXY_ENDPOINT))
    	        .awsAuthentication(AuthenticationType.AWS_V2_OR_V4, AWS_ACCESS_KEY, AWS_SECRET_KEY)
    	        .keyStore("C:/Windows/System32/KeyStore.jks", "mkjha1234")
    	        .build();
try {
    		if(!s3Proxy.getState().equals(AbstractLifeCycle.STARTED)) {
    			s3Proxy.start();
    		}
		} catch (Exception e) {
			logger.error("Exception occurred while starting S3 proxy: {}",e.getMessage());
		}
    	
    	Awaitility.await().until(() -> {
    		return s3Proxy.getState().equals(AbstractLifeCycle.STARTED);
    	});

s3 client code:

s3Client = AmazonS3ClientBuilder.standard()
        		.withCredentials(new AWSStaticCredentialsProvider(new BasicAWSCredentials(AWS_ACCESS_KEY, AWS_SECRET_KEY)))
        		.withEndpointConfiguration(new EndpointConfiguration(S3_PROXY_ENDPOINT, "us-east-1")).build();
        
        if(!s3Client.doesBucketExist(S3_BUCKET)) {
        	s3Client.createBucket(S3_BUCKET);
       }

**Comment by ddcprg** [comment]
You can find examples of how to use the rule in [circus-train](https://github.com/HotelsDotCom/circus-train). Here is a concrete example: https://github.com/HotelsDotCom/circus-train/blob/master/circus-train-s3-s3-copier/src/test/java/com/hotels/bdp/circustrain/s3s3copier/S3S3CopierTest.java#L82

With regards Cucumber, I know there are some issues with JUnit rules but I'm afraid I cannot tell. Perhaps refer to the issues in [cucumber-jvm](https://github.com/cucumber/cucumber-jvm)

**Comment by ddcprg** [comment]
Check this out -> https://github.com/cucumber/cucumber-jvm/tree/master/junit

I.e. you should be able to use `S3ProxyRule` as a `@ClassRule`

**Comment by MkJha** [comment]
I will explore on s3proxyRule, but since i am able to use s3Proxy and blobstore in cucumber. So right now main hurdle is to configure s3proxy as https. As i have explained above

**Comment by gaul** [comment]
It seems like either S3Proxy or the AWS SDK client is configured for HTTP and not HTTPS.  What is the value of `S3_PROXY_ENDPOINT`?  Looking at the S3Proxy test code at src/test/java/org/gaul/s3proxy/AwsSdkTest.java might also help.

**Comment by MkJha** [comment]
Your take is right. The error log you have seen above, that time i was not using secureendpoint method to set endpoint.

private static final String S3_PROXY_ENDPOINT = "https://127.0.0.1:443"; 
Now i get the below error 

com.amazonaws.SdkClientException: Unable to execute HTTP request: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1116)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1066)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4365)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4312)
	at com.amazonaws.services.s3.AmazonS3Client.headBucket(AmazonS3Client.java:1343)
	at com.amazonaws.services.s3.AmazonS3Client.doesBucketExist(AmazonS3Client.java:1283)


Proabably i am not generating keystore correctly.


I have used below command:

keytool -genkey -alias mydomain -keyalg RSA -keystore KeyStore.jks -keysize 2048

**Comment by MkJha** [comment]
I did the below steps and https endpoint worked: 

1. generate certificate   


keytool -genkey -alias localApps -keyalg RSA -keystore s3Proxy.jks -keysize 2048

 2. export key 

keytool -export -keystore s3Proxy.jks -alias localApps -file s3ProxyPub.cer

 3. import in java trusted keystore 


keytool -trustcacerts -keystore "C:\Program Files\Java\jdk1.8.0_66\jre\lib\security\cacerts" -storepass changeit -alias localApps -importcert -file  s3ProxyPub.cer

**Comment by MkJha** [comment]
But apart from this(in general): s3 proxy doesn't work if i give endpoint something like this:

http://localhost:8080, however it works if you give IP     http://127.0.0.1

is it expected ?

**Comment by gaul** [comment]
Which operating system do you use?  On Linux I can connect to S3Proxy configured with:

```
s3proxy.endpoint=http://localhost:8081
```

**Comment by MkJha** [comment]
I ran it on windows 10.

**Comment by gaul** [comment]
Can you ping localhost on this machine?  Perhaps you have a client configuration issue?  Either way it sounds like you have a workaround.  Did you resolve your original issue with cucumber and if so can we close this issue?

**Comment by gaul** [comment]
Closing due to inactivity.  Please reopen if symptoms persist.
