### ISSUE TITLE
Wiki example for swift unclear

### ISSUE THREAD

**Issue by bwalsh** [gaul/s3proxy#284]
The [wiki entry describing keystone authentication](https://github.com/gaul/s3proxy/wiki/Storage-backend-examples#swift-keystone-v20)   suggests the following configuration

```

docker run --rm -t -i --publish 80:80  \
  -e S3PROXY_AUTHORIZATION=none \
  -e JCLOUDS_PROVIDER=openstack-swift \
  -e JCLOUDS_ENDPOINT=$OS_AUTH_URL \
  -e JCLOUDS_REGION=$OS_REGION_NAME \
  -e JCLOUDS_IDENTITY=$OS_TENANT_NAME:$OS_USERNAME \
  -e JCLOUDS_CREDENTIAL=$OS_PASSWORD \
  --name s3proxy andrewgaul/s3proxy

```

This produced the following exception.

```
[s3proxy] W 10-08 14:55:31.931 main o.j.l.s.i.GetRegionIdMatchingProviderURIOrNull:74 |::] failed to find key for value http://10.96.11.20:5000/v2.0 in {RegionOne=http://10.96.11.20:8080/v1/AUTH_8897b62d8a8d45f38dfd2530375fbdac}; choosing first: RegionOne
Exception in thread "main" java.lang.IllegalArgumentException: region RegionOne not in []
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at org.jclouds.openstack.swift.v1.blobstore.RegionScopedBlobStoreContext.checkRegionId(RegionScopedBlobStoreContext.java:88)
	at org.jclouds.openstack.swift.v1.blobstore.RegionScopedBlobStoreContext.getBlobStore(RegionScopedBlobStoreContext.java:72)
	at org.jclouds.openstack.swift.v1.blobstore.RegionScopedBlobStoreContext.getBlobStore(RegionScopedBlobStoreContext.java:122)
	at org.gaul.s3proxy.Main.createBlobStore(Main.java:313)
	at org.gaul.s3proxy.Main.main(Main.java:112)
```

After some trial and error, I discovered that setting the JCLOUDS_REGIONS variable worked

```
docker run --rm -t -i --publish 80:80  \
  -e S3PROXY_AUTHORIZATION=none \
  -e JCLOUDS_PROVIDER=openstack-swift \
  -e JCLOUDS_ENDPOINT=$OS_AUTH_URL \
  -e JCLOUDS_REGIONS=$OS_REGION_NAME \
  -e JCLOUDS_REGION=$OS_REGION_NAME \
  -e JCLOUDS_IDENTITY=$OS_TENANT_NAME:$OS_USERNAME \
  -e JCLOUDS_CREDENTIAL=$OS_PASSWORD \
  --name s3proxy andrewgaul/s3proxy


[s3proxy] W 10-08 14:57:05.277 main o.j.l.s.i.GetRegionIdMatchingProviderURIOrNull:74 |::] failed to find key for value http://10.96.11.20:5000/v2.0 in {RegionOne=http://10.96.11.20:8080/v1/AUTH_8897b62d8a8d45f38dfd2530375fbdac}; choosing first: RegionOne
[s3proxy] I 10-08 14:57:05.349 main o.g.s.o.eclipse.jetty.util.log:186 |::] Logging initialized @2134ms
[s3proxy] I 10-08 14:57:05.430 main o.g.s.o.e.jetty.server.Server:327 |::] jetty-9.2.z-SNAPSHOT
[s3proxy] I 10-08 14:57:05.467 main o.g.s.o.e.j.s.ServerConnector:266 |::] Started ServerConnector@526cbe2d{HTTP/1.1}{0.0.0.0:80}
[s3proxy] I 10-08 14:57:05.468 main o.g.s.o.e.jetty.server.Server:379 |::] Started @2255ms
```

**Comment by gaul** [comment]
Can you make these changes to the wiki?  It is world-writable.
