### ISSUE TITLE
doesBucketExistV2 crashes when bucket doesnot exist on windows

### ISSUE THREAD

**Issue by nishantjain91samsung** [gaul/s3proxy#299]
`Exception in thread "main" com.amazonaws.services.s3.model.AmazonS3Exception: java.nio.file.NoSuchFileException: \tmp\s3proxy\test1 (Service: Amazon S3; Status Code: 500; Error Code: 500 java.nio.file.NoSuchFileException: \tmp\s3proxy\test1; Request ID: null; S3 Extended Request ID: null), S3 Extended Request ID: null
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1639)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4319)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4266)
	at com.amazonaws.services.s3.AmazonS3Client.getAcl(AmazonS3Client.java:3471)
	at com.amazonaws.services.s3.AmazonS3Client.getBucketAcl(AmazonS3Client.java:1168)
	at com.amazonaws.services.s3.AmazonS3Client.getBucketAcl(AmazonS3Client.java:1158)
	at com.amazonaws.services.s3.AmazonS3Client.doesBucketExistV2(AmazonS3Client.java:1293)`

**Comment by gaul** [comment]
Could you run this again with trace-level logging (`-DLOG_LEVEL=trace` from the command line)?  Unfortunately I do not have a Windows machine to test against.

**Comment by kerkhofsd** [comment]
Reproduced on Linux

**Comment by kerkhofsd** [comment]
Created a simple test in which the issue is reproduced.
