### ISSUE TITLE
Writing from Spark to S3proxy fails with FileAlreadyExistsException

### ISSUE THREAD

**Issue by brett--anderson** [gaul/s3proxy#302]
Using the docker image tagged latest for s3proxy with Spark 2.4.1 and Hadoop 2.7.3.

The following pyspark code works when connected to AWS S3:
```
df.write.mode("overwrite").save(
    "s3a://test-bucket/foo",
    format="json")
```
When I run this against s3proxy I get the following error:
```
org.apache.hadoop.fs.FileAlreadyExistsException: Path is a file: s3a://test-bucket/foo/_temporary/0
	at org.apache.hadoop.fs.s3a.S3AFileSystem.mkdirs(S3AFileSystem.java:853)
	at org.apache.hadoop.fs.FileSystem.mkdirs(FileSystem.java:1881)
...
```
Any ideas why I'm getting this error, how I could configure things differently to avoid it, or failing that, where to start on a patch for this behavior? Thanks.

**Comment by gaul** [comment]
Are you using the filesystem backend?  It has a limitation where if a file "foo" exists then you cannot create "foo/bar" since the filesystem already contains a foo file.

**Comment by gaul** [comment]
Closing due to inactivity; please reopen if symptoms persist.
