### ISSUE TITLE
Exception with s3cmd: Index 1 out of bounds for length 1

### ISSUE THREAD

**Issue by OdedRaiches** [gaul/s3proxy#335]
Hi, i'm having an issue with using s3cmd with s3proxy.
I'm trying to do this simple PUT command:
`s3cmd put stam.txt s3://https://blobeastus.blob.core.windows.net/oded-test1/stam.txt `

The output i'm getting is:
```
WARNING: Retrying failed request: //blobeastus.blob.core.windows.net/oded-test1/stam.txt (Tunnel connection failed: 500 Index 1 out of bounds for length 1)
WARNING: Waiting 3 sec...
upload: 'stam.txt' -> 's3://https://blobeastus.blob.core.windows.net/oded-test1/stam.txt'  [1 of 1]
[s3proxy] W 10-05 13:18:55.467 S3Proxy-Jetty-17 o.g.s.o.e.j.server.HttpChannel:396 |::] blobeastus.blob.core.windows.net:443
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at org.gaul.s3proxy.S3ProxyHandler.doHandle(S3ProxyHandler.java:629)
        at org.gaul.s3proxy.S3ProxyHandlerJetty.handle(S3ProxyHandlerJetty.java:76)
        at org.gaul.shaded.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.gaul.shaded.org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.gaul.shaded.org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.gaul.shaded.org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
        at org.gaul.shaded.org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at org.gaul.shaded.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.gaul.shaded.org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

From checking the sources I see this is the 629 line in S3ProxyHandler.java:
![image](https://user-images.githubusercontent.com/53560658/95079376-3638ba00-071f-11eb-9c59-f9700fb4a5c0.png)

Can anyone point me what is wrong with my input? 
Thanks!

**Comment by gaul** [comment]
>  `s3cmd put stam.txt s3://https://blobeastus.blob.core.windows.net/oded-test1/stam.txt `

Your s3:/// should not contain a full HTTP URL to Azure.  Instead it should just be the bucket name, probably `oded-test1`.  Here is a self-contained example:

```
s3cmd ls --host=127.0.0.1:8081 --access_key=local-identity --secret_key=local-credential --no-ssl s3://gaultest/
```

Instead configure the Azure endpoint in the `s3proxy.conf`.

**Comment by OdedRaiches** [comment]
@gaul thanks for the quick reply! the ls command works, but unfortunately PUT command does not:
input:
`s3cmd put stam.txt --host=127.0.0.1:8080 --access_key=local-identity --secret_key=local-credential --no-ssl s3://oded-test1/
`output:

```
WARNING: Module python-magic is not available. Guessing MIME types based on file extensions.
upload: 'stam.txt' -> 's3://oded-test1/stam.txt'  [1 of 1]
 29 of 29   100% in    0s    12.49 kB/s[s3proxy] W 10-05 17:51:32.065 S3Proxy-Jetty-19 o.j.a.s.h.AzureStorageClientErrorRetryHandler:74 |::] Cannot retry after server error, command is not replayable: [method=org.jclouds.azureblob.AzureBlobClient.public abstract java.lang.String org.jclouds.azureblob.AzureBlobClient.putBlob(java.lang.String,org.jclouds.azureblob.domain.AzureBlob)[oded-test1, [properties=[name=stam.txt, container=null, url=null, contentMetadata=[cacheControl=null, contentDisposition=null, contentEncoding=null, contentLanguage=null, contentLength=29, contentMD5=null, contentType=text/plain, expires=null], eTag=null, lastModified=null, leaseStatus=Unlocked, metadata={s3cmd-attrs=atime:1593703258/ctime:1601447140/gid:1021/gname:oded/md5:4b317b1bb0b39d971420b6a3ed1a08e1/mode:33188/mtime:1593703258/uid:1021/uname:oded}, type=BlockBlob]]], request=PUT https://blobeastus.blob.core.windows.net/oded-test1/stam.txt HTTP/1.1]
 29 of 29   100% in    0s    41.60 B/s  done
ERROR: Error parsing xml: Malformed error XML returned from remote server..  ErrorXML: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 </title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /oded-test1/stam.txt. Reason:
<pre>    Server rejected operation connecting to PUT https://blobeastus.blob.core.windows.net/oded-test1/stam.txt HTTP/1.1</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
</body>
</html>

WARNING: Upload failed: /stam.txt (500 (Server rejected operation connecting to PUT https://blobeastus.blob.core.windows.net/oded-test1/stam.txt HTTP/1.1))
```

**Comment by OdedRaiches** [comment]
@gaul 
I came across this compatibility list and tried to configure by it (using s3cmd version 2.0.1). After that I started getting:
```
WARNING: Could not refresh role
[s3proxy] E 10-06 09:44:46.924 S3Proxy-Jetty-15 o.gaul.s3proxy.S3ProxyHandler:622 |::] Unknown header x-amz-security-token with URI /oded-test1/
ERROR: S3 error: 501 (NotImplemented): A header you provided implies functionality that is not implemented.
```

Even after reverting to the old setting I kept getting this. Is there any cached configuration that i'm missing here?

**Comment by gaul** [comment]
s3cmd defaults to reading `$HOME/.s3cfg`.  This probably sets `access_token` which S3Proxy does not support.  You can check this by running `s3cmd --dump-config`.

**Comment by OdedRaiches** [comment]
@gaul 
Thanks a lot for the fast responses! 
Unfortunately I still have a problem with the PUT request that I mentioned here: https://github.com/gaul/s3proxy/issues/335#issuecomment-703686274

**Comment by OdedRaiches** [comment]
@gaul do you have any lead on the error I got on PUT command? thanks!
more in this comment: 
https://github.com/gaul/s3proxy/issues/335#issuecomment-703686274
