### ISSUE TITLE
Building s3proxy

### ISSUE THREAD

**Issue by nr-ey** [gaul/s3proxy#475]
I'm trying to build s3proxy locally. I can build and package it fine with `mvn package`, but when I try to ultimately run the docker image, I get errors. Any ideas? At first I thought dependencies were being excluded, so I added `<include>**</include>` to the shade plugin config, but that didn't work. Unfortunately my knowledge of the Java ecosystem is non-existent. (The official image from the Docker hub works fine, btw.)

```
46) [Guice/ErrorInCustomProvider]: IllegalArgumentException: No enum constant AuthType.
  at AzureBlobModule.AuthTypeFromPropertyOrDefault(AzureBlobModule.java:68)
      \_ installed by: AzureBlobHttpApiModule -> AzureBlobModule
  at StorageAccountInVhost.<init>(StorageAccountInVhost.java:43)
      \_ for 3rd parameter
  at StorageAccountInVhost.class(StorageAccountInVhost.java:31)
  while locating StorageAccountInVhost
  at SharedKeyLiteAuthentication.<init>(SharedKeyLiteAuthentication.java:97)
      \_ for 7th parameter
  at SharedKeyLiteAuthentication.class(SharedKeyLiteAuthentication.java:76)
  at AzureStorageUtils.signer(AzureStorageUtils.java:37)
      \_ for field signer
  at AzureStorageClientErrorRetryHandler.<init>(AzureStorageClientErrorRetryHandler.java:54)
      \_ for 2nd parameter
  while locating AzureStorageClientErrorRetryHandler
  at DelegatingRetryHandler.clientErrorRetryHandler(DelegatingRetryHandler.java:58)
      \_ for field clientErrorRetryHandler
  at DelegatingRetryHandler.class(DelegatingRetryHandler.java:55)
  at JavaUrlHttpCommandExecutorService.<init>(JavaUrlHttpCommandExecutorService.java:84)
      \_ for 3rd parameter
  at JavaUrlHttpCommandExecutorService.class(JavaUrlHttpCommandExecutorService.java:66)
  while locating JavaUrlHttpCommandExecutorService
  at JavaUrlHttpCommandExecutorServiceModule.configure(JavaUrlHttpCommandExecutorServiceModule.java:36)
  at InvokeHttpMethod.<init>(InvokeHttpMethod.java:60)
      \_ for 2nd parameter
  while locating InvokeHttpMethod
  at DelegatesToInvocationFunction.<init>(DelegatesToInvocationFunction.java:184)
      \_ for 5th parameter
  at AnnotatedHttpApiProvider.<init>(AnnotatedHttpApiProvider.java:45)
      \_ for 1st parameter
  at AnnotatedHttpApiProvider.class(AnnotatedHttpApiProvider.java:45)
  while locating AnnotatedHttpApiProvider<HttpClient>
  at UtilsImpl.<init>(UtilsImpl.java:52)
      \_ for 4th parameter
  at UtilsImpl.class(UtilsImpl.java:52)
  while locating UtilsImpl
  at ApiContextImpl.<init>(ApiContextImpl.java:48)
      \_ for 4th parameter
  at ApiContextImpl.class(ApiContextImpl.java:48)
  while locating ApiContextImpl<AzureBlobClient>
  while locating ApiContext<AzureBlobClient>
  at BindProviderMetadataContextAndCredentials.backend(BindProviderMetadataContextAndCredentials.java:84)
  at BlobStoreContextImpl.<init>(BlobStoreContextImpl.java:46)
      \_ for 1st parameter
  at BlobStoreContextImpl.class(BlobStoreContextImpl.java:46)
  while locating BlobStoreContextImpl
  while locating BlobStoreContext

Learn more:
  https://github.com/google/guice/wiki/ERROR_IN_CUSTOM_PROVIDER
Caused by: IllegalArgumentException: No enum constant AuthType.
	at java.base/Enum.valueOf(Unknown Source)
	at AuthType.valueOf(AuthType.java:23)
	at AuthType.fromValue(AuthType.java:35)
	at AzureBlobModule.AuthTypeFromPropertyOrDefault(AzureBlobModule.java:68)
	at AzureBlobModule$$FastClassByGuice$$3667325.GUICE$TRAMPOLINE(<generated>)
	at AzureBlobModule$$FastClassByGuice$$3667325.apply(<generated>)
	at ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:260)
	at ProviderMethod.doProvision(ProviderMethod.java:171)
	at InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
	at InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
	at SingleParameterInjector.inject(SingleParameterInjector.java:40)
	at SingleParameterInjector.getAll(SingleParameterInjector.java:60)
	at ConstructorInjector.provision(ConstructorInjector.java:113)
	at ConstructorInjector.construct(ConstructorInjector.java:91)
	at ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
	at ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at SingletonScope$1.get(SingletonScope.java:169)
	at InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at FactoryProxy.get(FactoryProxy.java:60)
	at SingleParameterInjector.inject(SingleParameterInjector.java:40)
	at SingleParameterInjector.getAll(SingleParameterInjector.java:60)
	at ConstructorInjector.provision(ConstructorInjector.java:113)
	at ConstructorInjector.construct(ConstructorInjector.java:91)
	at ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
	at ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at SingletonScope$1.get(SingletonScope.java:169)
	at InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at SingleFieldInjector.inject(SingleFieldInjector.java:50)
	at MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:146)
	at ConstructorInjector.provision(ConstructorInjector.java:124)
	at ConstructorInjector.construct(ConstructorInjector.java:91)
	at ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
	at SingleParameterInjector.inject(SingleParameterInjector.java:40)
	at SingleParameterInjector.getAll(SingleParameterInjector.java:60)
	at ConstructorInjector.provision(ConstructorInjector.java:113)
	at ConstructorInjector.construct(ConstructorInjector.java:91)
	at ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
	at FactoryProxy.get(FactoryProxy.java:60)
	at SingleFieldInjector.inject(SingleFieldInjector.java:50)
	at MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:146)
	at ConstructorInjector.provision(ConstructorInjector.java:124)
	at ConstructorInjector.construct(ConstructorInjector.java:91)
	at ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
	at ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at SingletonScope$1.get(SingletonScope.java:169)
	at InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at SingleParameterInjector.inject(SingleParameterInjector.java:40)
	at SingleParameterInjector.getAll(SingleParameterInjector.java:60)
	at ConstructorInjector.provision(ConstructorInjector.java:113)
	at ConstructorInjector.construct(ConstructorInjector.java:91)
	at ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
	at ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at SingletonScope$1.get(SingletonScope.java:169)
	at InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at FactoryProxy.get(FactoryProxy.java:60)
	at ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at SingletonScope$1.get(SingletonScope.java:169)
	at InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at SingleParameterInjector.inject(SingleParameterInjector.java:40)
	at SingleParameterInjector.getAll(SingleParameterInjector.java:60)
	at ConstructorInjector.provision(ConstructorInjector.java:113)
	at ConstructorInjector.construct(ConstructorInjector.java:91)
	at ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
	at FactoryProxy.get(FactoryProxy.java:60)
	at SingleParameterInjector.inject(SingleParameterInjector.java:40)
	at SingleParameterInjector.getAll(SingleParameterInjector.java:60)
	at ConstructorInjector.provision(ConstructorInjector.java:113)
	at ConstructorInjector.construct(ConstructorInjector.java:91)
	at ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
	at SingleParameterInjector.inject(SingleParameterInjector.java:40)
	at SingleParameterInjector.getAll(SingleParameterInjector.java:60)
	at ConstructorInjector.provision(ConstructorInjector.java:113)
	at ConstructorInjector.construct(ConstructorInjector.java:91)
	at ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
	at ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at SingletonScope$1.get(SingletonScope.java:169)
	at InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at BoundProviderFactory.get(BoundProviderFactory.java:58)
	at SingleParameterInjector.inject(SingleParameterInjector.java:40)
	at SingleParameterInjector.getAll(SingleParameterInjector.java:60)
	at ConstructorInjector.provision(ConstructorInjector.java:113)
	at ConstructorInjector.construct(ConstructorInjector.java:91)
	at ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
	at ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at SingletonScope$1.get(SingletonScope.java:169)
	at InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at FactoryProxy.get(FactoryProxy.java:60)
	at SingleParameterInjector.inject(SingleParameterInjector.java:40)
	at SingleParameterInjector.getAll(SingleParameterInjector.java:60)
	at ConstructorInjector.provision(ConstructorInjector.java:113)
	at ConstructorInjector.construct(ConstructorInjector.java:91)
	at ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
	at ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at SingletonScope$1.get(SingletonScope.java:169)
	at InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at FactoryProxy.get(FactoryProxy.java:60)
	at InjectorImpl$1.get(InjectorImpl.java:1100)
	at InjectorImpl.getInstance(InjectorImpl.java:1133)
	at BindProviderMetadataContextAndCredentials.backend(BindProviderMetadataContextAndCredentials.java:84)
	at BindProviderMetadataContextAndCredentials$$FastClassByGuice$$12594691.GUICE$TRAMPOLINE(<generated>)
	at BindProviderMetadataContextAndCredentials$$FastClassByGuice$$12594691.apply(<generated>)
	at ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:260)
	at ProviderMethod.doProvision(ProviderMethod.java:171)
	at InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
	at InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
	at ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at SingletonScope$1.get(SingletonScope.java:169)
	at InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at SingleParameterInjector.inject(SingleParameterInjector.java:40)
	at SingleParameterInjector.getAll(SingleParameterInjector.java:60)
	at ConstructorInjector.provision(ConstructorInjector.java:113)
	at ConstructorInjector.construct(ConstructorInjector.java:91)
	at ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
	at ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at SingletonScope$1.get(SingletonScope.java:169)
	at InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at FactoryProxy.get(FactoryProxy.java:60)
	at InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
	at InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
	at InternalInjectorCreator.build(InternalInjectorCreator.java:113)
	at Guice.createInjector(Guice.java:87)
	at ContextBuilder.buildInjector(ContextBuilder.java:405)
	at ContextBuilder.buildInjector(ContextBuilder.java:328)
	at ContextBuilder.buildView(ContextBuilder.java:615)
	at ContextBuilder.buildView(ContextBuilder.java:595)
	at ContextBuilder.build(ContextBuilder.java:588)
	at Main.createBlobStore(Main.java:355)
	at Main.main(Main.java:121)
```

**Comment by nr-ey** [comment]
Never mind, this was a config issue on my end. For future readers, I had to also define S3PROXY_V4_MAX_NON_CHUNKED_REQ_SIZE and JCLOUDS_AZUREBLOB_AUTH.
