### ISSUE TITLE
filesystem blobstore does not atomically replace objects

### ISSUE THREAD

**Issue by davidp1404** [gaul/s3proxy#490]
Hello, I am using the latest s3proxy image with the filesystem backend in our development environment.
In our use case we have concurrent access to blobs but when we modify blobs we see that s3proxy report "NoSuchKey when calling the GetObject operation" eventually.
This issue is related to the old reported one in https://issues.apache.org/jira/browse/JCLOUDS-835 that seems to be solved years ago, but seems to fail the s3 commitment "a mutating operation like write or overwrite should succeed and expose the new object or fail and retain the old object."
Is there any explanation to the filesystem backend doesn't implement atomic behavior?
The issue can be reproduced with this code:
```
$ cat qa-reader.py
import boto3
import os
import socket
import time
import urllib3
urllib3.disable_warnings()
s3_url = os.environ['s3_url']
pid = os.getpid()
hostname = socket.gethostname()
client = boto3.client(
    's3',
    endpoint_url=s3_url,
    aws_access_key_id="demouser",
    aws_secret_access_key="demouser123",
    verify=False
)
while True:
    obj = client.get_object(Bucket='qa-test', Key='qa-file.txt')
    msg = obj['Body'].read().decode('utf-8')
    print(msg,end='\r')

$ cat qa-writer.py
import boto3
import os
import socket
import time

s3_url = os.environ['s3_url']
pid = os.getpid()
hostname = socket.gethostname()
client = boto3.client(
    's3',
    endpoint_url=s3_url,
    aws_access_key_id="demouser",
    aws_secret_access_key="demouser123",
    verify=False
)
while True:
    msg = f"Updated by {hostname} (pid={pid})"
    client.put_object(Bucket='qa-test', Key='qa-file.txt', Body=str(msg))
    print("File updated +",end='\r')
    time.sleep(200/1000)
    print("File updated #",end='\r')

$ s3_url='http://127.0.0.1:9102' python qa-writer.py &
$ s3_url='http://127.0.0.1:9102' python qa-reader.py
Traceback (most recent call last):69605)
  File "qa-reader.py", line 19, in <module>
    obj = client.get_object(Bucket='qa-test', Key='qa-file.txt')
  File "/home/k8sadmin/s3-qatest/.venv/lib/python3.8/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/k8sadmin/s3-qatest/.venv/lib/python3.8/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
```
Thanks in advance!

**Comment by gaul** [comment]
Confirmed that this is a problem.  This is a regression from apache/jclouds@ab25fc7259ad620a4daa14c12a37cef498320ad5 that I suspect was introduced to work around Windows strange behavior.  I am happy to revert these lines from FilesystemStorageStrategyImpl.putBlob:

```java
if (outputFile.exists()) {
   delete(outputFile);
}
```

Note that we should keep the exception handling.  Note that the filesystem blobstore needs many improvements, in this case calling `Files.remove(outputFile.toPath())` has more concise error propagation.  Can you submit a PR?

**Comment by davidp1404** [comment]
Hello Andrew, sorry but java is not a language I feel comfortable with so I'd appreciate it if you could release a corrected version of s3proxy that we could use.
Thanks in advance.

**Comment by gaul** [comment]
I committed a partial fix to jclouds where the object will not disappear when being replaced.  However, there is a related issue where the object can change while being fetched that requires further work.  The symptoms are a mismatch between the expected and actual Content-Length.

**Comment by davidp1404** [comment]
Thanks very much @gaul, looking forward to the new release including this fix.

**Comment by gaul** [comment]
Still thinking about this in apache/jclouds#165.

**Comment by gaul** [comment]
Partial fix on master: [`c764d34`](https://github.com/gaul/s3proxy/commit/c764d34) takes a blob's
length from the descriptor that serves the bytes (`FileChannel.size()`) rather than from an earlier
stat of the path. A descriptor refers to one file for as long as it is held, so the declared
Content-Length and the body can no longer describe different versions.

Measured with 3 writers alternating a 100 B and a 500,000 B body on one key against 8 concurrent
readers, 30s, ~60k GETs each run:

```
                        before    after
truncated response       2365        0
HTTP 500 (overrun)       1319        0
ETag mismatch              19     1197
NoSuchKey                   0        0
```

**The metadata is still not read atomically, and that is what is left of this issue.** It is not
only the ETag: the user metadata, the `Content-*` headers, the storage class and `Last-Modified` are
all read through the path in `getBlobInternal`, which resolves anew on every call. `putBlob`
publishes by renaming a new file over the key, so a put landing between two of those reads — or
between them and the open that follows — answers with more than one version of the object. The
payload's length is now exempt; nothing else can be.

Note the ETag column above goes **up**. That is the same race becoming visible rather than becoming
more common: requests that used to die as a truncated response now complete with the right length
and a stale ETag. Quieter, and a complete valid body beats a broken one, but a client that verifies
checksums still fails and one that does not now silently accepts a body whose ETag names a
different write.

**Why it is not simply fixed.** In C the whole request would be served from one descriptor:

```c
fd = open(path, O_RDONLY);
fstat(fd, &st);        /* size, mtime */
fgetxattr(fd, ...);    /* ETag, user metadata */
read(fd, ...);         /* bytes */
```

A rename cannot touch an inode already held, so there is no race and nothing to detect. NIO has no
counterpart to `fstat(2)` or `fgetxattr(2)`. Checked against the JDK with `javap`:

* `Files.readAttributes` — both overloads take a `Path`. No overload accepts a `FileChannel`, a
  `SeekableByteChannel` or a `FileDescriptor`.
* `Files.getFileAttributeView` — likewise `Path` only. This is the sole route to
  `UserDefinedFileAttributeView`, where the ETag and user metadata live, so there is no way at all
  to read an xattr from a file you already have open.
* `FileChannel` — `size()`, `position()`, and nothing else of this kind. No modification time, no
  user-defined attributes. `size()` being available is exactly why the length could be fixed and
  the rest could not.
* `/proc/self/fd/N` is not a way out either: `FileChannel` does not expose its descriptor, and
  `java.io.FileDescriptor` keeps its integer package-private (`valid()` and `sync()` are the only
  public methods besides the three standard streams).

So every metadata read re-resolves the name, and the backend cannot pin one version of an object
for the duration of a request.

**What would close it:** store the metadata where the bytes are — a header in the object file, read
through the same descriptor — instead of in xattrs. That makes the read the C shape above and
removes the race at its source rather than detecting it afterwards. It is a storage format change
and would need a migration path for existing data.

The alternative is to detect and retry: stat, read xattrs, open, stat again, and compare
`BasicFileAttributes.fileKey()` (device and inode on POSIX, which a rename cannot preserve),
starting over when it moved. I prototyped that and did not keep it — it is a retry loop in the read
path plus a new failure mode under a writer that never pauses, all of it machinery that exists only
to work around the missing API.

There is a comment to this effect at the top of `getBlobInternal` so the next reader does not have
to rediscover it.
