### ISSUE TITLE
AWS SDK issue

### ISSUE THREAD

**Issue by kevparang** [gaul/s3proxy#549]
I get this for some reason when uploading an image. 

Error uploading image: Error [XMLParserError]: Unexpected close tag
Line: 5
Column: 7
Char: >
    at error (C:\Users\balev\node_modules\sax\lib\sax.js:667:10)
    at strictFail (C:\Users\balev\node_modules\sax\lib\sax.js:693:7)
    at closeTag (C:\Users\balev\node_modules\sax\lib\sax.js:887:9)
    at SAXParser.write (C:\Users\balev\node_modules\sax\lib\sax.js:1449:13)
    at exports.Parser.Parser.parseString (C:\Users\balev\node_modules\xml2js\lib\parser.js:327:31)
    at Parser.parseString (C:\Users\balev\node_modules\xml2js\lib\parser.js:5:59)       
    at NodeXmlParser.parse (C:\Users\balev\node_modules\aws-sdk\lib\xml\node_parser.js:31:10)
    at Request.extractError (C:\Users\balev\node_modules\aws-sdk\lib\services\s3.js:697:39)
    at Request.callListeners (C:\Users\balev\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at Request.emit (C:\Users\balev\node_modules\aws-sdk\lib\sequential_executor.js:78:10) {
  code: 'XMLParserError',
  retryable: true,
  time: 2023-08-28T00:25:50.394Z,
  statusCode: 413
}

**Comment by gaul** [comment]
Can you be more specific about which AWS SDK you are using and how to reproduce these symptoms?  https://github.com/aws/aws-sdk-js-v3 does not appear to have an `s3.js` for example.

**Comment by kevparang** [comment]
Seems like it was a max file issue. I sorted it out.
