### ISSUE TITLE
GetObjectAsync(request) Failure ETAG

### ISSUE THREAD

**Issue by kevin-miller-13** [gaul/s3proxy#555]
When I make a call to retrieve an Azure blob I get : _"Specified argument was out of the range of valid values. (Parameter 'hex')
   at Amazon.Util.AWSSDKUtils.HexStringToBytes(String hex)"_

Upon investigation I traced it to the amazons3client checking for an Etag that should have an even number of hex digits.

Help???

**Comment by gaul** [comment]
Can you be more specific about how this error occurs, e.g., which SDK you use and the full stack trace?

**Comment by kevin-miller-13** [comment]
Sure, sorry should have done so already:

SDK : AWSSDK.S3 (3.7.205.3)

STACK TRACE (from postman) :
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'hex')
   at Amazon.Util.AWSSDKUtils.HexStringToBytes(String hex)
   at Amazon.S3.Internal.AmazonS3ResponseHandler.ProcessResponseHandlers(IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ResponseHandler.PostInvoke(IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Signer.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at MyWebApp.Classes.CloudService.DownloadDocumentByNameAsync(String name, Boolean shouldThrow) in C:\Temp\Kubernetes3\KubernetesTestApp\Classes\CloudService.cs:line 59
   at TestStorageApp.Controllers.S3ProxyController.Download() in C:\Temp\Kubernetes3\KubernetesTestApp\S3ProxyController.cs:line 36
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.<>c__DisplayClass33_0.<WrapVoidMethod>b__0(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.VoidResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

HEADERS
=======
Accept: */*
Host: localhost:5226
User-Agent: PostmanRuntime/7.32.3
Accept-Encoding: gzip, deflate, br
Cache-Control: no-cache
Content-Type: multipart/form-data; boundary=--------------------------681190203900673980201566
Content-Length: 175
Postman-Token: c95945f4-c08f-49f8-8d87-cfee5b9efc91

**Comment by ZHAO-SHI-HAO** [comment]
@gaul I have same exception occur, and when I try azureblob-sdk, it behaves the same. Will it be repaired in the future?

**Comment by stumct-sa** [comment]
I have run into this issue recently with the AWS .NET SDK. As far as I can see there is no viable configuration options to bypass this.

https://github.com/aws/aws-sdk-net/blob/aaf537237542cffd9d5440ed151e9bb0b7f8eaca/sdk/src/Services/S3/Custom/Internal/AmazonS3ResponseHandler.cs#L112
