### ISSUE TITLE
Build Failure on Windows

### ISSUE THREAD

**Issue by bossrhino** [gaul/s3proxy#634]
I'm a bit new to this.  But  Iended up having a build failure when running `mvn package`.  Pulled the latest version from github.  And am building on a Windows 11 laptop.

Maven Version 3.9.6
Java Version 19.0.1

Not sure where I should look to troubleshoot.  Hoping to be pointed in the right direction:

```
[INFO]
[ERROR] Failures:
[ERROR]   AwsSdkTest.testSpecialCharacters:594
Expected size: 1 but was: 0 in:
[]
[INFO]
[ERROR] Tests run: 114, Failures: 1, Errors: 0, Skipped: 2
[INFO]
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
[ERROR] Tests run: 156, Failures: 2, Errors: 0, Skipped: 15, Time elapsed: 51.40 s <<< FAILURE! -- in TestSuite
[ERROR] org.gaul.s3proxy.JcloudsS3ClientLiveTest.JcloudsS3ClientLiveTest -- Time elapsed: 0.020 s <<< FAILURE!
java.lang.AssertionError: expected [1] but found [0]
        at org.testng.Assert.fail(Assert.java:110)
        at org.testng.Assert.failNotEquals(Assert.java:1413)
        at org.testng.Assert.assertEqualsImpl(Assert.java:149)
        at org.testng.Assert.assertEquals(Assert.java:131)
        at org.testng.Assert.assertEquals(Assert.java:1240)
        at org.testng.Assert.assertEquals(Assert.java:1274)
        at org.jclouds.s3.S3ClientLiveTest.testUnusualKeyCharacters(S3ClientLiveTest.java:564)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:136)
        at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:658)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:219)
        at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
        at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:923)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:192)
        at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
        at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1589)

[ERROR] org.gaul.s3proxy.EncryptedBlobStoreLiveTest.EncryptedBlobStoreLiveTest -- Time elapsed: 0.007 s <<< FAILURE!
java.lang.AssertionError: expected [1] but found [0]
        at org.testng.Assert.fail(Assert.java:110)
        at org.testng.Assert.failNotEquals(Assert.java:1413)
        at org.testng.Assert.assertEqualsImpl(Assert.java:149)
        at org.testng.Assert.assertEquals(Assert.java:131)
        at org.testng.Assert.assertEquals(Assert.java:1240)
        at org.testng.Assert.assertEquals(Assert.java:1274)
        at org.jclouds.s3.S3ClientLiveTest.testUnusualKeyCharacters(S3ClientLiveTest.java:564)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:136)
        at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:658)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:219)
        at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
        at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:923)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:192)
        at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
        at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1589)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR] org.gaul.s3proxy.EncryptedBlobStoreLiveTest.EncryptedBlobStoreLiveTest
[INFO]   Run 1: PASS
[INFO]   Run 2: PASS
[INFO]   Run 3: PASS
[INFO]   Run 4: PASS
[INFO]   Run 5: PASS
[INFO]   Run 6: PASS
[INFO]   Run 7: PASS
[INFO]   Run 8: PASS
[INFO]   Run 9: PASS
[INFO]   Run 10: PASS
[INFO]   Run 11: PASS
[INFO]   Run 12: PASS
[INFO]   Run 13: PASS
[INFO]   Run 14: PASS
[INFO]   Run 15: PASS
[INFO]   Run 16: PASS
[INFO]   Run 17: PASS
[INFO]   Run 18: PASS
[INFO]   Run 19: PASS
[INFO]   Run 20: PASS
[INFO]   Run 21: PASS
[INFO]   Run 22: PASS
[INFO]   Run 23: PASS
[INFO]   Run 24: PASS
[INFO]   Run 25: PASS
[ERROR]   Run 26: EncryptedBlobStoreLiveTest>S3ClientLiveTest.testUnusualKeyCharacters:564 expected [1] but found [0]
[INFO]   Run 27: PASS
[INFO]
[ERROR] org.gaul.s3proxy.JcloudsS3ClientLiveTest.JcloudsS3ClientLiveTest
[INFO]   Run 1: PASS
[INFO]   Run 2: PASS
[INFO]   Run 3: PASS
[INFO]   Run 4: PASS
[INFO]   Run 5: PASS
[INFO]   Run 6: PASS
[INFO]   Run 7: PASS
[INFO]   Run 8: PASS
[INFO]   Run 9: PASS
[INFO]   Run 10: PASS
[INFO]   Run 11: PASS
[INFO]   Run 12: PASS
[INFO]   Run 13: PASS
[INFO]   Run 14: PASS
[INFO]   Run 15: PASS
[INFO]   Run 16: PASS
[INFO]   Run 17: PASS
[INFO]   Run 18: PASS
[INFO]   Run 19: PASS
[INFO]   Run 20: PASS
[INFO]   Run 21: PASS
[INFO]   Run 22: PASS
[ERROR]   Run 23: JcloudsS3ClientLiveTest>S3ClientLiveTest.testUnusualKeyCharacters:564 expected [1] but found [0]
[INFO]   Run 24: PASS
[INFO]
[INFO]
[ERROR] Tests run: 101, Failures: 2, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.gaul.s3proxy.junit.S3ProxyExtensionTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.997 s -- in org.gaul.s3proxy.junit.S3ProxyExtensionTest
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:46 min
[INFO] Finished at: 2024-05-13T11:46:46-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.2.5:test (default-test) on project s3proxy: There are test failures.
[ERROR]
[ERROR] Please refer to D:\Work\Git\s3proxy\s3proxy\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by gaul** [comment]
Since this works on Linux and in CI I suspect that this is a Windows issue.  I don't have such a device to test so you will need to investigate the test failures.  If you don't care about those you can skip them with `mvn package -DskipTests=true`.

**Comment by bossrhino** [comment]
I was about to ask you to close this.  -DskipTests=true appears to have fixed the problem.  It seemed to build and deploy to docker without issue on my end.  Apologize for the long post.  But hopefully this helps someone in the future.
